# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animals', models.BooleanField(default=False)),
                ('kids', models.BooleanField(default=False)),
                ('fails', models.BooleanField(default=False)),
                ('stereotypes', models.BooleanField(default=False)),
                ('language', models.BooleanField(default=False)),
                ('absurd', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
